name: nob

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: build
      run: git submodule update --init --recursive
           cc -o nob nob.c
           ./nob
      
    - name: test
      run: ./nob test
